apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: messaging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: management
      port: 15672
      targetPort: 15672
